name: dynamixelshield_ci

on:
  push:
  pull_request:

jobs:
  dynamixelshield_ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Run Arduino CI Script (PR)
        run: |
          echo ${{github.head_ref}};
          echo ${{github.event_name}};
        if: ${{github.event_name}} == 'pull_request'          
      - name: Run Arduino CI Script (Push)
        run: |
          echo ${{github.ref}};
          echo ${{github.event_name}};
        if: ${{github.event_name}} == 'push'          
