name: dynamixelshield_ci

on:
  push:
  pull_request:

jobs:
  dynamixelshield_ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Run Arduino CI Script (PR)
        if: github.event_name == 'pull_request'     
        run: |
          ${{github.head_ref}}
      - name: Run Arduino CI Script (Push)
        if: github.event_name == 'push'
        run: |
          ${{github.ref_name}}

